import type { Metadata } from "next";
export const metadata: Metadata={title:"Governed AI Output & Cost-Optimized Model Selection",description:"Pipelix enforces your UI, coding, API, and test contracts on every AI run, and automatically routes each task to the most cost-effective model that can do the job.",alternates:{canonical:"/benefits"},openGraph:{url:"/benefits",title:"Governed AI Output & Cost-Optimized Model Selection | Pipelix",description:"Consistent, contract-governed output—at the lowest model cost that gets the job done."}};
const contracts=[["UI contract","Design system, component patterns, and accessibility rules applied to every generated interface."],["Coding standards contract","Your style guide, architecture patterns, and security rules—enforced, not suggested."],["API & interface contract","Stable request/response shapes, error handling, and naming conventions across services."],["Test & quality contract","Coverage expectations, frameworks, and validation gates every change must pass before handoff."]];
const faq=[["What are Pipelix contracts?","Written specifications—UI, coding standards, API, and test contracts—that define how your team expects code to look and behave. Pipelix applies them automatically to every run instead of relying on each developer's prompt."],["How does auto model selection save money?","Pipelix classifies each task by complexity and risk, then routes it to the least expensive model capable of doing it correctly—reserving premium models for the work that actually needs them."],["Does a cheaper model mean lower quality?","No. Model selection is scoped to task fit, not a blanket downgrade, and every run still passes through the same validation and review gates regardless of which model executed it."],["Can we bring our own contracts?","Yes. Pipelix is designed to enforce the standards your team already has—existing style guides, design systems, and API conventions—rather than impose new ones."]];
export default function Page(){const schema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map(([name,text])=>({"@type":"Question",name,acceptedAnswer:{"@type":"Answer",text}}))};return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
 <header className="site-header"><a className="brand" href="/"><img src="/favicon.svg" alt=""/><span>Pipelix</span></a><nav aria-label="Main navigation"><a href="/watch">Watch demo</a><a href="/azure-devops-ai-agent">Azure DevOps AI Agent</a><a href="/routines">Routines</a><a href="/about">About</a></nav><a className="btn compact" href="/#contact">Book a demo <span>↗</span></a></header>
 <section className="seo-hero"><span className="eyebrow">Governed output. Optimized cost.</span><h1>Consistent AI output, at the <span>lowest model cost that works.</span></h1><p>Pipelix enforces your team's written contracts on every run and automatically selects the most cost-effective model capable of the task—so output stays consistent and developers stop burning tokens and budget on trial and error.</p><div className="hero-actions"><a className="btn" href="/#contact">Book a workflow review <span>↗</span></a><a className="watch" href="#contracts">See how it's governed</a></div></section>
 <section className="section seo-grid" id="contracts">{contracts.map(([t,c])=><article key={t}><b>◆</b><h2>{t}</h2><p>{c}</p></article>)}</section>
 <section className="section problem" id="model-selection"><div className="kicker">Auto model selection</div><div className="split"><h2>Stop paying premium-model<br/>prices for every task.<br/><span>Pay for what the task needs.</span></h2><div><p>Not every task needs your most expensive model. Pipelix classifies each run by complexity and risk, then automatically routes it to the least expensive model that can execute it correctly—reserving premium models for work that genuinely requires them.</p><p>Developers never choose a model, tune a prompt for cost, or babysit token spend. The routing decision happens once, per task, inside a governed execution that's already validated before it reaches review.</p></div></div><div className="stats"><article><b>1</b><h3>Model decision per task</h3><p>Chosen automatically by task complexity—never left to manual, inconsistent prompting.</p></article><article><b>0</b><h3>Developer hours spent model-shopping</h3><p>No one manually swaps models to chase cost or quality.</p></article><article><b>100%</b><h3>Runs still fully validated</h3><p>Regardless of which model executes a task, every run passes the same quality gates.</p></article></div></section>
 <section className="section seo-copy"><span className="kicker">Why it matters</span><h2>Centralized execution beats a hundred individual prompts.</h2><p>When every developer prompts an AI tool independently, you get inconsistent output, duplicated cleanup work, and unpredictable spend—because no one is enforcing a shared standard or watching the cost per task. Pipelix centralizes both: your contracts govern what "correct" looks like, and automatic model selection governs what it costs to get there.</p><ul><li>Contracts apply the same rules whether the change is trivial or complex</li><li>Model routing scales cost to task difficulty, not habit</li><li>Engineers review outcomes—not inconsistent formatting or overpriced runs</li></ul></section>
 <section className="section faq seo-faq"><div><span className="kicker">Frequently asked questions</span><h2>Governance and cost, answered.</h2></div><div>{faq.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
 <section className="seo-cta"><h2>Bring your contracts. We'll handle the model bill.</h2><p>We'll map your existing standards and show what cost-optimized, governed execution looks like on a real workflow.</p><a className="btn" href="/#contact">Request a workflow review <span>↗</span></a></section>
</main>}
