"use client";
import { FormEvent, useState } from "react";

const flow = [
  ["01", "Intake", "Sync work items, bugs, support tickets, priorities, and acceptance criteria."],
  ["02", "Prepare", "Investigate the task, inspect the repo, and build an implementation-ready plan."],
  ["03", "Build + verify", "Implement changes, run validation, and independently verify the outcome."],
  ["04", "Deliver + measure", "Create an auditable handoff and measure engineering impact."],
];

function Logo(){return <a className="brand" href="#top" aria-label="Pipelix home"><img src="/favicon.svg" alt=""/><span>Pipelix</span></a>}

function ControlPlane(){return <div className="control-plane" aria-label="Pipelix task execution preview">
  <div className="cp-top"><div><span className="task-icon">P</span><p><small>AZURE DEVOPS · AB#36830</small><b>Improve checkout reliability</b></p></div><span className="azure-pill">◆ Azure DevOps</span></div>
  <div className="cp-meta"><span className="active">● Executing</span><span>Priority 2</span><span>AcmeInc / Retail Platform</span><em>07m 14s</em></div>
  <div className="cp-stages"><div className="done"><i>✓</i><b>Intake</b><small>Synced</small></div><div className="done"><i>✓</i><b>Prepare</b><small>Approved</small></div><div className="running"><i>✦</i><b>Build + verify</b><small>Running</small></div><div><i>4</i><b>Deliver</b><small>Queued</small></div></div>
  <div className="cp-cards"><article><header>Task orchestration <span>Live</span></header><div className="queue"><p><i className="purple"/>Planning <b>1</b></p><p><i className="orange"/>Blocked <b>2</b></p><p><i className="blue"/>In progress <b>2</b></p><p><i className="green"/>Done <b>47</b></p></div></article><article><header>AI execution <span>Verified</span></header><p className="log"><b>10:48</b> Plan approved<br/><b>10:49</b> Pipelix Engineer updated 6 files<br/><b>10:52</b> Build passed<br/><b>10:54</b> Regression tests running</p><div className="diff"><b>+184</b><b>−21</b><span>3 commits</span></div></article><article><header>Run evidence <span>Passing</span></header><div className="score"><b>24/24</b><span>tests passed</span></div><p className="checks">✓ Build passed<br/>✓ Security scan passed<br/>✓ 92% coverage<br/>◌ E2E validation running</p></article></div>
  <div className="cp-foot"><span>✦ AI-selected execution model</span><span>Branch: feature/checkout-reliability</span><b>Audit trail active</b></div>
 </div>}

export default function Home(){const [sent,setSent]=useState(false);function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const subject=encodeURIComponent(`Pipelix workflow review — ${d.get("company")}`);const body=encodeURIComponent(`Name: ${d.get("name")}\nEmail: ${d.get("email")}\nCompany: ${d.get("company")}\nTeam size: ${d.get("team")}\n\n${d.get("message")}`);setSent(true);window.location.href=`mailto:hello@pipelix.ai?subject=${subject}&body=${body}`}
return <main id="top">
 <header className="site-header"><Logo/><nav aria-label="Main navigation"><a href="#platform">Platform</a><a href="#workflow">Workflow</a><a href="#azure">Azure DevOps</a><a href="#results">Results</a><a href="#faq">FAQ</a></nav><a className="btn compact" href="#contact">Book a demo <span>↗</span></a></header>
 <section className="hero"><div className="hero-copy"><div className="eyebrow">✦ AI engineering operations platform</div><h1>Turn your backlog into <span>verified code delivery.</span></h1><p>Pipelix orchestrates, executes, validates, and measures development work—directly from Azure DevOps—while your engineers stay in control.</p><div className="hero-actions"><a className="btn" href="#contact">Book a workflow review <span>↗</span></a><a className="watch" href="#workflow"><i>▶</i> See how it works</a></div><div className="trust"><b>◆ Azure DevOps ready</b><span>Built for engineering teams that need more delivery capacity.</span></div></div><div className="hero-ui"><ControlPlane/></div></section>
 <section className="proof"><div><i>▦</i><span><b>Task orchestration</b><small>Organize and route work</small></span></div><div><i>◆</i><span><b>Azure DevOps integration</b><small>Boards, repos, and pipelines</small></span></div><div><i>⬡</i><span><b>Validated AI delivery</b><small>Evidence before handoff</small></span></div><div><i>↗</i><span><b>15×+ team leverage</b><small>Measurable business impact</small></span></div></section>
 <section className="section problem" id="platform"><div className="kicker">Controlled execution—not another coding assistant</div><div className="split"><h2>Accelerate delivery.<br/>Give engineers leverage.<br/><span>Give leaders visibility.</span></h2><div><p>Most engineering teams have more valuable work than capacity. Bugs wait. Service tickets interrupt. Technical debt grows. Senior developers spend their time coordinating repetitive execution.</p><p>Pipelix turns that work into a controlled AI operation—with preparation, model selection, validation, review, recovery, and complete evidence built into every run.</p></div></div><div className="stats" id="results"><article><b>Up to 25×</b><h3>Engineering leverage potential</h3><p>Scale delivery capacity with the work you assign.</p></article><article><b>~7<sup> min</sup></b><h3>Average task time</h3><p>Based on current Pipelix execution workflows.</p></article><article><b>24/7</b><h3>Backlog throughput</h3><p>Run a single task or a governed work queue.</p></article></div></section>
 <section className="section workflow" id="workflow"><div className="section-title"><div><span className="kicker">How Pipelix works</span><h2>From work item intake to measurable delivery.</h2></div><p>Your team defines the work and the guardrails. Pipelix executes the repeatable engineering workflow and makes every stage visible.</p></div><div className="flow-grid">{flow.map(([n,t,c])=><article key={n}><span>{n}</span><div className="flow-icon">{n==="01"?"◆":n==="02"?"⌕":n==="03"?"✦":"↗"}</div><h3>{t}</h3><p>{c}</p></article>)}</div></section>
 <section className="azure section" id="azure"><div className="azure-copy"><span className="kicker">Azure DevOps integration</span><h2>Keep your boards, repos, pipelines, and engineering process.</h2><p>Pipelix works as an execution layer around the tools your team already trusts—not as a disconnected replacement.</p><ul><li><i>✓</i><span><b>Work begins in Azure Boards</b><small>Sync tasks, bugs, acceptance criteria, priorities, and updates.</small></span></li><li><i>✓</i><span><b>Code stays in your repositories</b><small>Honor project, branch, and pull-request boundaries.</small></span></li><li><i>✓</i><span><b>Your pipelines remain quality gates</b><small>Run the builds and regression suites your team relies on.</small></span></li><li><i>✓</i><span><b>Delivery stays audit-ready</b><small>Plans, logs, files, validation, and outcomes remain traceable.</small></span></li></ul><a href="#contact">Explore your integration →</a></div><div className="integration"><div className="az-card"><b>◆</b><span>Azure DevOps<small>Boards · Repos · Pipelines</small></span></div><div className="connection"><i/><i/><i/></div><div className="px-card"><img src="/favicon.svg" alt=""/><span>Pipelix<small>AI orchestration</small></span></div><div className="outputs"><span><b>01</b> Execution plan</span><span><b>02</b> Code changes</span><span><b>03</b> Test evidence</span><span><b>04</b> Review handoff</span></div></div></section>
 <section className="section roles"><span className="kicker">Built for the whole delivery organization</span><h2>More leverage at every level.</h2><div className="role-grid"><article><span>CTO / CIO</span><h3>Increase delivery capacity</h3><p>Move more roadmap and technical-debt work without expanding headcount at the same rate.</p></article><article><span>Engineering lead</span><h3>Protect team focus</h3><p>Delegate repeatable work while preserving standards, review gates, and technical visibility.</p></article><article><span>Product manager</span><h3>Shorten backlog cycle time</h3><p>Turn well-scoped work into testable outcomes with fewer handoffs and clearer progress.</p></article><article><span>Engineer</span><h3>Stay on hard problems</h3><p>Use Pipelix as execution leverage—not a black box—and review every meaningful result.</p></article></div></section>
 <section className="section faq" id="faq"><div><span className="kicker">Common questions</span><h2>Clear answers before you connect a repo.</h2><p>We start with a workflow review to identify the right starting project, controls, and success measures.</p></div><div>{[["Does Pipelix replace developers?","No. Pipelix gives developers execution leverage. Your team defines the work, standards, permissions, and review gates."],["Can it work across multiple repos and branches?","Yes. Each Pipelix project can connect to its own repository and workflow, with isolated branches and project-specific rules."],["What work is a good fit?","Defined feature work, bug fixes, service desk tickets, regression tests, performance improvements, documentation, and repeatable engineering work."],["How can we evaluate it safely?","Start with a bounded workflow and noncritical backlog. We establish access, branching, validation, and review policies before execution."]].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
 <section className="section contact" id="contact"><div><span className="kicker">Start with your real workflow</span><h2>See what Pipelix could take off your team’s plate.</h2><p>Tell us how your team uses Azure DevOps and where delivery gets stuck. We’ll map one practical workflow and show how Pipelix would execute it.</p><ul><li>✓ Technical workflow review</li><li>✓ Built around your repositories and process</li><li>✓ No pricing presentation</li></ul></div><form onSubmit={submit}><div className="form-row"><label>Name<input name="name" required placeholder="Your name"/></label><label>Work email<input type="email" name="email" required placeholder="you@company.com"/></label></div><div className="form-row"><label>Company<input name="company" required placeholder="Company name"/></label><label>Development team size<select name="team" defaultValue=""><option value="" disabled>Select team size</option><option>1–5 engineers</option><option>6–20 engineers</option><option>21–50 engineers</option><option>51+ engineers</option></select></label></div><label>What would you like Pipelix to help with?<textarea name="message" required placeholder="Tell us about your backlog, workflow, or a task your team repeats..."/></label><button className="btn" type="submit">Request a workflow review <span>↗</span></button><small className={sent?"sent":""}>{sent?"Your email app is opening with your request ready to send.":"We’ll use this information only to respond to your request."}</small></form></section>
 <footer><Logo/><p>AI engineering operations for Azure DevOps teams.</p><nav><a href="#platform">Platform</a><a href="#azure">Azure DevOps</a><a href="#contact">Contact</a></nav><small>© 2026 Pipelix. All rights reserved.</small></footer>
 </main>}
