import type { Metadata } from "next";
export const metadata: Metadata={title:"Automated Engineering Routines",description:"Turn recurring engineering work—performance tuning, service tickets, error remediation, and backlog prep—into scheduled Pipelix routines.",alternates:{canonical:"/routines"},openGraph:{url:"/routines",title:"Automated Engineering Routines | Pipelix",description:"Set the schedule or trigger once. Pipelix runs the routine, validates the result, and delivers evidence every time."}};
const routines=[["Auto performance tuning","Continuously profile hot paths, flag regressions, and ship verified performance fixes on a recurring cadence."],["Service ticket triage & fixes","Pick up new support tickets automatically, reproduce the issue, and deliver a tested fix with evidence attached."],["Error log & alert remediation","Watch logs and monitoring alerts around the clock, diagnose root cause, and open a verified pull request."],["PBI & work item preparation","Groom the backlog automatically: draft acceptance criteria, technical breakdowns, and estimates before planning."],["Dependency & patch updates","Keep packages and security patches current with tested, low-risk upgrade pull requests."],["Regression test maintenance","Detect flaky or outdated tests and keep the suite aligned with the current codebase."]];
const steps=[["01","Define the trigger","Choose a schedule—daily, weekly, on demand—or an event trigger like a new ticket, failed build, or incoming work item."],["02","Set the guardrails","Scope the repositories, branches, quality gates, and approval requirements the routine must respect."],["03","Pipelix executes","Every run investigates, implements, and validates automatically—no manual kickoff required."],["04","Review the evidence","Each run produces a plan, diff, test results, and audit trail so your team reviews outcomes, not busywork."]];
const faq=[["What counts as a routine?","Any repeatable engineering workflow you can define clearly enough to schedule or trigger—performance tuning, ticket handling, log remediation, backlog grooming, dependency upgrades, and more."],["Do routines skip review?","No. Every run produces the same plan, validation, and evidence as a manual Pipelix task before anything reaches production."],["Can routines run on a schedule and on events?","Yes. Configure a fixed cadence (daily, weekly) or an event trigger such as a new ticket, failed build, or incoming work item—or both."],["Can we change or stop a routine?","Yes. Adjust scope, guardrails, or cadence at any time, or pause a routine without affecting the others."]];
export default function Page(){const schema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map(([name,text])=>({"@type":"Question",name,acceptedAnswer:{"@type":"Answer",text}}))};return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
 <header className="site-header"><a className="brand" href="/"><img src="/favicon.svg" alt=""/><span>Pipelix</span></a><nav aria-label="Main navigation"><a href="/watch">Watch demo</a><a href="/azure-devops-ai-agent">Azure DevOps AI Agent</a><a href="/benefits">Benefits</a><a href="/about">About</a></nav><a className="btn compact" href="/#contact">Book a demo <span>↗</span></a></header>
 <section className="seo-hero"><span className="eyebrow">Scheduled AI engineering routines</span><h1>Turn recurring work into <span>routines that run themselves.</span></h1><p>Set the schedule or trigger once. Pipelix executes the routine, validates every run against your quality gates, and delivers evidence—so recurring engineering work stops competing with your roadmap.</p><div className="hero-actions"><a className="btn" href="/#contact">Book a workflow review <span>↗</span></a><a className="watch" href="#examples">See routine examples</a></div></section>
 <section className="section seo-grid routines-grid" id="examples">{routines.map(([t,c])=><article key={t}><b>◆</b><h2>{t}</h2><p>{c}</p></article>)}</section>
 <section className="section seo-copy"><span className="kicker">And that's just the start</span><h2>If it's a repeatable engineering workflow, it can become a routine.</h2><p>Auto tuning, ticket handling, and log remediation are the routines teams start with—but the model applies to any well-scoped, repeatable workflow: documentation sync, changelog generation, dependency audits, test-suite upkeep, and whatever repetitive work is unique to your backlog. The opportunities are effectively endless.</p></section>
 <section className="section workflow" id="how-it-works"><div className="section-title"><div><span className="kicker">How routines work</span><h2>Define it once. Pipelix runs it every time.</h2></div><p>Routines use the same governed execution as any Pipelix task—preparation, validation, review, and evidence—just on a schedule or trigger you control.</p></div><div className="flow-grid">{steps.map(([n,t,c])=><article key={n}><span>{n}</span><div className="flow-icon">{n==="01"?"◆":n==="02"?"⌕":n==="03"?"✦":"↗"}</div><h3>{t}</h3><p>{c}</p></article>)}</div></section>
 <section className="section faq seo-faq"><div><span className="kicker">Frequently asked questions</span><h2>Automate with the same guardrails.</h2><p>Routines don't lower the bar for what reaches production—they apply your existing standards on autopilot.</p></div><div>{faq.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
 <section className="seo-cta"><h2>Pick one recurring task. Turn it into a routine.</h2><p>We'll map the trigger, guardrails, and success criteria before scheduling your first routine.</p><a className="btn" href="/#contact">Request a workflow review <span>↗</span></a></section>
</main>}
